Reproduce issue 479.
This is to illustrate https://github.com/prometheus/client_golang/issues/479

For this to run, you need to serve an HTTP 500 error on localhost:80.
I did this with the following nginx snippet:
```
	error_page 500 /500.html;
	location /api/v1/query {
		return 500;
	}
```
and the following file in `/var/www/html`:
```
$ head /var/www/html/500.html
important troubleshooting detail
$
```

Then running the test suite shows:
```
--- FAIL: TestReproIssue479 (0.00s)
    api_test.go:720: querying failed with [bad_response: bad response code 500]. Details: [important troubleshooting detail]
FAIL
```